In [2]:
import cplex
import os
import datetime
import sys
import numpy as np
import pandas as pd
import pickle

In [61]:
path = "..//test//"  #Attention!!!!!! Changer test par Data_RTE
read_path = path+"Problem_RTE//"
write_path = path+"OurSolution_RTE//"
files = os.listdir(read_path) #obtenir tous les noms sous le ficher
print(files)

['problem-1-1-20190923-142640.mps', 'problem-1-1-20190923-142645.mps', 'problem-1-2-20190923-142652.mps']


In [62]:
prob = cplex.Cplex()

In [63]:
start_time = datetime.datetime.now()

sol_list = []
seconds_membres = []
noms = []
for file in files:
    prob.read(read_path+file)
    prob.solve()
    ind = int(file[-5])
    ind = ind + 1
    objective_value = prob.solution.get_objective_value()    
    sol_list.append(objective_value)
    seconds_membres.append(prob.linear_constraints.get_rhs())
    noms.append(file[7:-5]+str(ind))
end_time = datetime.datetime.now()
execution_time = end_time - start_time #calcule le temps d'exécution


Selected objective sense:  MINIMIZE
Selected objective  name:  OBJECTIF
Selected RHS        name:  RHSVAL
Selected bound      name:  BNDVALUE


17931 Column-fixed warnings not printed.


CPXPARAM_Read_DataCheck                          1
Parallel mode: deterministic, using up to 4 threads for concurrent optimization.
Tried aggregator 1 time.
LP Presolve eliminated 43578 rows and 38350 columns.
Aggregator did 2439 substitutions.
Reduced LP has 72697 rows, 78827 columns, and 560440 nonzeros.
Presolve time = 0.36 sec. (199.05 ticks)
Initializing dual steep norms . . .

Iteration log . . .
Iteration:     1   Dual objective     =     376966393.994610
Iteration:   920   Dual objective     =     842276924.671217
Iteration:  1700   Dual objective     =     873575680.954683
Iteration:  2505   Dual objective     =     880212127.724112
Iteration:  3338   Dual objective     =     897309750.895511
Iteration:  4188   Dual objective     =     901486348.644928
Iteration:  5128   Dual objective     =     911868490.474870
Iteration:  5843   Dual objective     =     914908813.608228
Iteration:  6682   Dual objective     =     916036775.617282
Iteration:  7601   Dual objective     =     9

17931 Column-fixed warnings not printed.


CPXPARAM_Read_DataCheck                          1
Parallel mode: deterministic, using up to 4 threads for concurrent optimization.
Tried aggregator 1 time.
LP Presolve eliminated 61880 rows and 49978 columns.
Aggregator did 2463 substitutions.
Reduced LP has 54371 rows, 67175 columns, and 214772 nonzeros.
Presolve time = 0.31 sec. (150.75 ticks)
Initializing dual steep norms . . .

Iteration log . . .
Iteration:     1   Dual objective     =     575389537.183154
Iteration:   868   Dual objective     =     813360619.434793
Iteration:  1814   Dual objective     =     886476501.542120
Iteration:  2581   Dual objective     =     896203756.119167
Iteration:  3347   Dual objective     =     903993326.853390
Iteration:  4165   Dual objective     =     917527129.004552
Iteration:  4934   Dual objective     =     919054593.607464
Iteration:  5796   Dual objective     =     922032286.174042
Iteration:  6559   Dual objective     =     924743288.984826
Iteration:  7203   Dual objective     =     9

18220 Column-fixed warnings not printed.


CPXPARAM_Read_DataCheck                          1
Parallel mode: deterministic, using up to 4 threads for concurrent optimization.
Tried aggregator 1 time.
LP Presolve eliminated 43177 rows and 38353 columns.
Aggregator did 2441 substitutions.
Reduced LP has 73096 rows, 78822 columns, and 617110 nonzeros.
Presolve time = 0.41 sec. (206.99 ticks)
Initializing dual steep norms . . .

Iteration log . . .
Iteration:     1   Dual objective     =     380448420.518828
Iteration:   955   Dual objective     =     925456494.118816
Iteration:  1780   Dual objective     =     948357073.468370
Iteration:  2389   Dual objective     =     955335084.155459
Iteration:  3410   Dual objective     =     978174489.374527
Iteration:  4275   Dual objective     =     981822461.779584
Iteration:  5160   Dual objective     =     984840185.991894
Iteration:  5917   Dual objective     =     987673854.374724
Perturbation started.
Iteration:  6161   Dual objective     =     987865672.431481
Iteration:  6867   Dual

In [64]:
print(execution_time)

0:00:16.339907


In [66]:
#seconds_membres = pd.DataFrame(seconds_membres)
#seconds_membres.to_csv("SecondMembers_test.csv")  #write data
tableau_solutions = np.array([])

In [67]:
#df = pd.read_csv("SecondMembers_test.csv",index_col=0) #read data
#print(df)
#pickle.dump(seconds_membres, open("SecondMember_test", "wb"))
def genere_seconds_membres(seconds_membres, noms):
    n = len(seconds_membres[0])
    r = []
    for i in range(len(seconds_membres)):
        assert len(seconds_membres[i]) == n
        r.append((np.array(seconds_membres[i]), noms[i]))
    return r
pickle.dump(genere_seconds_membres(seconds_membres, noms), open("SecondMember_test.pickle","wb"))# remplacer par SecondMembers


In [68]:
def genere_solutions(sol_list,noms):
    assert len(sol_list) == len(noms)
    r = []
    for i in range(len(sol_list)):
        r.append((sol_list[i],noms[i]))
    return r
pickle.dump(genere_solutions(sol_list, noms), open("OurSolutions_test.pickle","wb"))# remplacer par OurSolutions


In [69]:
def charge_seconds_membres():
    import pickle
    l = pickle.load(open("SecondMember_test.pickle","rb"))# A changer par l = pickle.load(open("SecondMember.pickle","rb"))
    seconds_membres = []
    noms = []
    for (second_membre, nom) in l:
        seconds_membres.append(second_membre)
        noms.append(nom)
    return (np.array(seconds_membres), noms)


In [70]:
def charge_solutions():
    import pickle
    l = pickle.load(open("OurSolutions_test.pickle", "rb"))
    solutions = []
    noms = []
    for (solution, nom) in l:
        solutions.append(solution)
        noms.append(nom)
    return (np.array(solutions), noms)


In [71]:
def verifie_noms(noms1, noms2):
    assert len(noms1) == len(noms2)
    for i in range(len(noms1)):
        assert noms1[i] == noms2[i]

In [72]:
### Pour un chargement complet 
array_seconds_membres, noms_seconds_membres = charge_seconds_membres()
vect_solutions, noms_solutions = charge_solutions()
verifie_noms(noms_solutions, noms_seconds_membres)


In [129]:
print(type(vect_solutions))
print(array_seconds_membres.shape)

<class 'numpy.ndarray'>
(3, 118714)


In [154]:
print(array_seconds_membres)

[[-2.363e+03  3.496e+03 -6.008e+03 ...  5.000e+00  5.000e+00  5.000e+00]
 [-2.363e+03  3.496e+03 -6.008e+03 ...  5.000e+00  5.000e+00  5.000e+00]
 [-2.433e+03  3.440e+03 -6.319e+03 ...  5.000e+00  5.000e+00  5.000e+00]]


In [155]:
print(noms_seconds_membres)

['-1-1-20190923-142641', '-1-1-20190923-142646', '-1-2-20190923-142653']


In [156]:
print(vect_solutions)

[9.24983458e+08 9.25816969e+08 9.94911375e+08]


### Une autre méthode pour charger les données 0 signifie les seconds membres et 1 signifie les noms

In [3]:
df=np.array(pd.DataFrame(pd.read_pickle("SecondMember_test.pickle"))[0])
print(df)

[array([-2.363e+03,  3.496e+03, -6.008e+03, ...,  5.000e+00,  5.000e+00,
        5.000e+00])
 array([-2.363e+03,  3.496e+03, -6.008e+03, ...,  5.000e+00,  5.000e+00,
        5.000e+00])
 array([-1748.,  3944., -3911., ...,     4.,     4.,     4.]) ...
 array([-1.843e+03,  3.758e+03, -5.370e+03, ...,  5.000e+00,  5.000e+00,
        5.000e+00])
 array([-2.434e+03,  3.266e+03, -6.060e+03, ...,  5.000e+00,  5.000e+00,
        5.000e+00])
 array([-2.434e+03,  3.266e+03, -6.060e+03, ...,  5.000e+00,  5.000e+00,
        5.000e+00])]


In [9]:
df=np.vstack(np.array(pd.DataFrame(pd.read_pickle("SecondMember_test.pickle"))[1]))
print(df)

[['-1-1-20190923-142641']
 ['-1-1-20190923-142646']
 ['-1-10-20190923-142804']
 ...
 ['-9-8-20190923-1427310']
 ['-9-9-20190923-142745']
 ['-9-9-20190923-142747']]
